// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcWave.Data;

#nullable disable

namespace MvcWave.Migrations
{
    [DbContext(typeof(MvcWaveContext))]
    [Migration("20240823192637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MvcWave.Models.Wave", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("accurateRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("humanRelation")
                        .HasColumnType("TEXT");

                    b.Property<int>("max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("optimalScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("raw")
                        .HasColumnType("TEXT");

                    b.Property<int>("realMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("realMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Wave");
                });
#pragma warning restore 612, 618
        }
    }
}
